### ISSUE TITLE
Can we use Events and Callback Functions?

### ISSUE THREAD

**Issue by KyleKing** [jantimon/meteor-gpio#3]
Would it possible to call `GPIO.add_event_detect(24, GPIO.RISING, callback=etc...)` from Meteor, like [what can be done in python](http://makezine.com/projects/tutorial-raspberry-pi-gpio-pins-and-python/)?

EDIT: It looks like there is an NPM package that might be able to do this: https://www.npmjs.com/package/rpi-gpio

**Comment by jantimon** [comment]
Yes thats what the onoff module does - however this would not push the gpio status to the frontend
